/*
 * instructions.h
 *
 *  Created on: Oct 12, 2025
 *      Author: Arlen Feng
 */

#ifndef CORE_INSTRUCTIONS_H_
#define CORE_INSTRUCTIONS_H_

#include <stdbool.h>
#include "core_state.h"

/*** Instruction Definitions ***/

#define GENERIC_INVALID_INSTR 0xFFFF

typedef enum instruction_type{
	EXECUTE_MACHINE_LANGUAGE_SUBROUTINE,
	CLEAR_SCREEN,
	RETURN_FROM_SUBROUTINE,
	JUMP,
	EXECUTE_SUBROUTINE,
	SKIP_IF_VALUE_VX_EQUALS_NN,
	SKIP_IF_VALUE_VX_NOT_EQUALS_NN,
	SKIP_IF_VALUE_VX_EQUALS_VALUE_VY,
	STORE_NN_IN_VX,
	ADD_NN_TO_VX,
	STORE_VALUE_VY_IN_VX,
	SET_VX_TO_VX_OR_VY,
	SET_VX_TO_VX_AND_VY,
	SET_VX_TO_VX_XOR_VY,
	ADD_VALUE_VY_TO_VX,
	SUBTRACT_VALUE_VY_FROM_VX,
	STORE_VALUE_VY_SHIFTED_RIGHT_ONE_BIT_TO_VX,
	SET_VX_TO_VALUE_VY_MINUX_VX,
	STORE_VALUE_VY_SHIFTED_LEFT_ONE_BIT_TO_VX,
	SKIP_IF_VALUE_VX_NOT_EQUAL_TO_VALUE_VY,
	STORE_NNN_IN_REGISTER_I,
	JUMP_TO_ADDRESS_NNN_PLUS_V0,
	SET_VX_TO_RANDOM_NUMBER_WITH_MASK_OF_NN,
	DRAW_SPRITE,
	SKIP_IF_KEY_STORED_IN_VX_PRESSED,
	SKIP_IF_KEY_STORED_IN_VX_NOT_PRESSED,
	STORE_VALUE_DELAY_TIMER_IN_VX,
	WAIT_FOR_KEY_PRESS,
	SET_DELAY_TIMER_TO_VALUE_VX,
	SET_SOUND_TIMER_TO_VALUE_VX,
	ADD_VALUE_VX_TO_REGISTER_I,
	SET_I_TO_MEMORY_ADDRESS_OF_SPRITE_DATA,
	STORE_BINARY_CODED_DECIMAL_EQUIVALENT,
	STORE_VALUES_V0_VX,
	FILL_REGISTERS_V0_VX,
	INVALID_INSTRUCTION_TYPE
} instruction_type;

typedef struct instruction_result{
	instruction_type type;
	bool success;
	char* custom_message;
} instruction_result;

/*** Public Function Declarations ***/

instruction_result execute_instruction(uint16_t instruction, core_state* state);

#endif /* CORE_INSTRUCTIONS_H_ */
